name: expense_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/Group 77.png
   - assets/Vector.png
   - assets/Subtract.png
   - assets/Aboutus.png
   - assets/Category.png
   - assets/Graphs.png
   - assets/Subtract.png
   - assets/medicine.png
   - assets/image.png
